# Generated by Django 5.0.7 on 2024-07-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='piso',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
