# Generated by Django 5.0.7 on 2024-07-27 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_habitacion_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='piso',
            field=models.CharField(default='planta baja', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nhabitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.habitacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
