version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hotel_network

  # Backend Django
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=myproject.settings.development
      - DATABASE_URL=postgresql://hotel_user:hotel_password@db:5432/hotel_db
    depends_on:
      - db
    networks:
      - hotel_network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_AI_URL=http://localhost:8081
      - WATCHPACK_POLLING=true
    depends_on:
      - web
    networks:
      - hotel_network
    stdin_open: true
    tty: true

  # LLM local con Ollama (dev)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - hotel_network

  # AI Gateway (FastAPI) consumiendo el backend y Ollama (dev)
  ai_gateway:
    build:
      context: ./ai-gateway
      dockerfile: Dockerfile
    environment:
      - BACKEND_BASE_URL=http://web:8000/api
      - OPENAPI_SCHEMA_URL=http://web:8000/api/schema/
      - OLLAMA_BASE_URL=http://ollama:11434
      - MODEL_NAME=llama3.1:8b
      - SERVICE_USERNAME=admin
      - SERVICE_PASSWORD=admin123
    ports:
      - "8081:8081"
    depends_on:
      - web
      - ollama
    networks:
      - hotel_network

volumes:
  postgres_data:
  static_volume:
  ollama_data:

networks:
  hotel_network:
    driver: bridge
