# Generated by Django 5.0.7 on 2024-07-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(default='doble', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.CharField(default='Seleccionar', max_length=100)),
                ('nhabitacion', models.CharField(default='Indicar', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(default='Apellido', max_length=100)),
                ('personas', models.IntegerField(default=1)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('noches', models.IntegerField(default=1, editable=False)),
                ('precio_por_noche', models.FloatField(default=0, editable=False)),
                ('monto_total', models.FloatField()),
                ('senia', models.FloatField()),
                ('resto', models.FloatField(editable=False)),
                ('cantidad_habitaciones', models.IntegerField(default=1)),
                ('telefono', models.CharField(default='1', max_length=20)),
                ('celiacos', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('origen', models.CharField(default='Seleccionar', max_length=100)),
            ],
        ),
    ]
