# Generated by Django 5.0.6 on 2024-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_habitacion_piso_alter_reserva_nhabitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='encargado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='origen',
            field=models.CharField(max_length=100),
        ),
    ]
