# Generated by Django 5.0.6 on 2025-02-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_encargado_alter_reserva_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
    ]
